--- #YAML:1.0
name:               RPC-Lite
version:            0.20
abstract:           A lightweight yet flexible framework for remote process communication.
author:
    - Andrew Burke <aburke@bitflood.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:     0
    IO::Select:       0
    IO::Socket:       0
    JSON:             1.07
    threads:          0
    threads::shared:  0
    XML::Simple:      2.14
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
